POST http://localhost:3001/api/user/newUser
Content-Type: application/json

{
    "username": "testuser",
    "password": "password",
    "recipes":["https://edamam.co.uk/stuff", "https://edamam.com/things"]
}